// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-gDIrPjkFssc0E89mN-wU7QxRfYcou68',
    appId: '1:172736066305:web:4aff5589db9c67144f6100',
    messagingSenderId: '172736066305',
    projectId: 'comfort-connect-9f74d',
    authDomain: 'comfort-connect-9f74d.firebaseapp.com',
    storageBucket: 'comfort-connect-9f74d.appspot.com',
    measurementId: 'G-H47LFXHVVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2CNEY-hzgObjBOxdiZ-5xKH8NPuK1BPU',
    appId: '1:172736066305:android:00dc3bfcf247f0da4f6100',
    messagingSenderId: '172736066305',
    projectId: 'comfort-connect-9f74d',
    storageBucket: 'comfort-connect-9f74d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPiVRls4Vr0XHeqtKOWG2Aqrm_HQL2_7E',
    appId: '1:172736066305:ios:5abb43143b6278e54f6100',
    messagingSenderId: '172736066305',
    projectId: 'comfort-connect-9f74d',
    storageBucket: 'comfort-connect-9f74d.appspot.com',
    iosClientId: '172736066305-13nie71rgm2jlgsk0rjvgj5e8vfsch8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPiVRls4Vr0XHeqtKOWG2Aqrm_HQL2_7E',
    appId: '1:172736066305:ios:5abb43143b6278e54f6100',
    messagingSenderId: '172736066305',
    projectId: 'comfort-connect-9f74d',
    storageBucket: 'comfort-connect-9f74d.appspot.com',
    iosClientId: '172736066305-13nie71rgm2jlgsk0rjvgj5e8vfsch8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkspace',
  );
}
